### PR TITLE
docs(recording/sim_time): replace APIs

### PR DESCRIPTION
**Pull request by takeshi-iwanari**
## Description

Replace old APIs with new APIs

## Related links

None

## Notes for reviewers

None

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Comment by takeshi-iwanari** [comment]
@atsushi421 
Could you review this? I made very minor fixes to fit with new APIs.

**Review by atsushi421 — CHANGES_REQUESTED** [review]
@takeshi-iwanari 
Thank you for doing the document corrections that I had forgotten to do myself.
Could you also add `save()` method to the API examples?
```
def save(
    self,
    export_path: str,
    title: str = '',
    xaxis_type: Optional[str] = None,
    ywheel_zoom: Optional[bool] = None,
    full_legends: Optional[bool] = None
) -> None:
```

**Comment by takeshi-iwanari** [comment]
@atsushi421 
Thank you for pointing it out! I missed it.
It was fixed in 3865317da180ba4f4eeb3c146aaf5b1ca31389d2

**Review by atsushi421 — APPROVED** [review]
LGTM!

**Pull request merged**
