### PR TITLE
docs: fix documents for time-series visualization API

### PR DESCRIPTION
**Pull request by atsushi421**
Signed-off-by: atsushi421 <a.yano.578@ms.saitama-u.ac.jp>

## Description
This PR modifies pages related to the time-series data visualization API to use the new interface `create_[Metrics]_[VisualizationMethod]_plot(target_object)`.

In the recently merged [refactoring of the Plot package](https://github.com/tier4/CARET_analyze/pull/170), the interface `create_[Metrics]_[VisualizationMethod]_plot(target_object)` was added for time series data.
The previous interface `create_[TargetObject]_[Metrics]_plot(target_object)` is still available, but we think it is better to move to the new interface for future extensibility.

## Related links
- JIRA ticket: https://tier4.atlassian.net/browse/T4PB-21471
- Interface Modification PR: https://github.com/tier4/CARET_analyze/pull/170

## Notes for reviewers
To reduce conflicts with [ongoing PR](https://github.com/tier4/CARET_doc/pull/119), I have written the documents with reference to it.

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Comment by atsushi421** [comment]
@takam5f2 
Could you please review this?

**Comment by takam5f2** [comment]
@atsushi421  
Could you change direction of this PR to the branch to be merged in #119 ?

**Comment by atsushi421** [comment]
@takam5f2 
The merge target has been changed.
Since this branch was created from latest `main` branch, synchronizing `main` will reduce the difference.

**Comment by takam5f2** [comment]
@atsushi421  
I had misunderstanding. Let me change the direction as previous.

**Comment by takam5f2** [comment]
@atsushi421  
Excuse me for repeating, could you check the following PR?
https://github.com/atsushi421/CARET_doc/pull/1

**Review by takam5f2 — APPROVED** [review]
LTGM

**Comment by takam5f2** [comment]
@atsushi421  Thank you for your contribution.
@hsgwa @keita1523  I have merged #119 to this branch. If you have any concerns, please tell us till 3:00 p.m. tomorrow. If there is no comment, I'd like to merge. Thanks,

**Comment by takam5f2** [comment]
@atsushi421 @hsgwa @keita1523 
It's time to merge this PR. Thank you for your work and review.

**Pull request merged**
