### PR TITLE
ci(cspell-check): change referred cspell dictionary.

### PR DESCRIPTION
**Pull request by takam5f2**
Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>

### CODE REVIEW

**Comment by takam5f2** [comment]
@hsgwa  

After merging this PR, CARET_doc will refer to https://github.com/tier4/cspell-dicts/ for spell checking.

**Comment by kenji-miyake** [comment]
@takam5f2 Actually, I guess you don't need to import the dictionary here. The dictionaries in `tier4/cspell-dicts` are automatically loaded.

So you can delete `.cspell.json` instead.
But if you want, it's okay to keep it.

**Comment by takam5f2** [comment]
@kenji-miyake  
Thank you for your feedback. I have removed .cspell.json, but `spell-check-differential` outputted some errors. 
It seems that `"import": ["@tier4/cspell-dicts/caret/cspell-ext.json"]` should be described in any .cspell.json.

**Comment by kenji-miyake** [comment]
Ah, right! I'm sorry I was wrong.
https://github.com/tier4/autoware-spell-check-dict/blob/54d4409cdbb309bf1cc948ef0b340e57f083c741/.cspell.json#L47

**Comment by kenji-miyake** [comment]
You can add it to `autoware-spell-check-dict/.cspell.json` or you can manage it here.

**Comment by takam5f2** [comment]
@kenji-miyake  
Thank you for advice.

I'd like to manage `.cspell.json` dedicated for CARET project here by ourselves. Mixing CARET-dedicated `.cspell.json` in `autoware-spell-check-dict/.cspell.json` is not preferred for Autoware project.

**Comment by kenji-miyake** [comment]
I see. Sounds good!

**Review by hsgwa — APPROVED** [review]
LGTM

**Pull request merged**
