### PR TITLE
chore: align words of usage flow between figure and text

### PR DESCRIPTION
**Pull request by takam5f2**
Corresponding to https://github.com/tier4/CARET_doc/pull/47 , I'd like to align words of usage flow between figure and text.

Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>

### CODE REVIEW

**Comment by hsgwa** [comment]
@takam5f2 
dead links
- https://github.com/tier4/CARET_doc/runs/6586873865?check_suite_focus=true#step:3:242
- https://github.com/tier4/CARET_doc/runs/6586873865?check_suite_focus=true#step:3:142

**Review by hsgwa — CHANGES_REQUESTED** [review]
@takam5f2 
dead links
- https://github.com/tier4/CARET_doc/runs/6586873865?check_suite_focus=true#step:3:242
- https://github.com/tier4/CARET_doc/runs/6586873865?check_suite_focus=true#step:3:142

**Comment by takam5f2** [comment]
@hsgwa  
I completely resolved all links which are missed.

**Review by hsgwa — APPROVED** [review]
LGTM

**Pull request merged**
