### PR TITLE
docs: reconstruct documentation

### PR DESCRIPTION
**Pull request by takam5f2**
Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>

### CODE REVIEW

**Comment by takam5f2** [comment]
@hsgwa @takeshi-iwanari @keita1523 @bopeng-saitama  
Could you check if your page is not lost or changed unintentionally?

**Review by takeshi-iwanari — APPROVED** [review]
LGTM
Thank you for you work!!

**Review by hsgwa — APPROVED** [review]
LGTM!

I confirmed pre-commit-optional test passes and each commit for broken links.
Thank you!

**Review by bopeng-saitama — APPROVED** [review]
LGTM.
I confirmed that there are no obvious problems with the Visualization chapter.
Thank you for you work.

**Pull request merged**
